# Generated by Django 5.0.4 on 2024-06-19 10:37

import moon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countNumber', models.IntegerField(validators=[moon.models.NatureNumbersValidator])),
            ],
        ),
    ]
