# Generated by Django 5.0.4 on 2024-05-10 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='^[A-Z]\\w*$')])),
                ('author', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(255)])),
                ('label', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(255)])),
                ('producer', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(255)])),
                ('genre', models.CharField(choices=[('rock', 'Rock'), ('rap', 'Rap'), ('hiphop', 'Hiphop'), ('classical', 'Classical'), ('pop', 'Pop'), ('bluze', 'Bluze')], max_length=255)),
                ('year', models.IntegerField(max_length=255, validators=[django.core.validators.MinValueValidator(1995), django.core.validators.MaxValueValidator(2025)])),
            ],
        ),
    ]
